[project]
name = "render-workflows-django-example"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "daphne>=4.2.2",
    "dj-database-url>=3.1.2",
    "django>=6.0.6",
    "django-allauth>=65.18.0",
    "django-anymail>=15.0",
    "django-htmx>=1.27.0",
    "django-tailwind[cookiecutter,honcho,reload]>=4.5.0",
    "psycopg2-binary>=2.9.12",
    "render-sdk>=0.7.0",
    "uvicorn>=0.49.0",
    "whitenoise>=6.12.0",
]

[dependency-groups]
dev = [
    "zensical>=0.0.46",
]
