# Generated by Django 6.0.7 on 2026-07-28 03:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busybee', '0002_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('country', models.CharField(help_text='ISO 3166-1 alpha-2 country code, e.g. AU.', max_length=2)),
                ('latitude', models.DecimalField(decimal_places=5, max_digits=8)),
                ('longitude', models.DecimalField(decimal_places=5, max_digits=8)),
                ('timezone', models.CharField(default='UTC', help_text='IANA timezone name, e.g. Australia/Sydney.', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'cities',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='HourlyWeather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observed_at', models.DateTimeField(help_text='Start of the hour this reading covers, in UTC.')),
                ('temperature_c', models.FloatField(help_text='Air temperature in degrees Celsius.')),
                ('feels_like_c', models.FloatField(blank=True, help_text='Apparent temperature in degrees Celsius.', null=True)),
                ('humidity', models.PositiveSmallIntegerField(help_text='Relative humidity, 0-100%.')),
                ('pressure_hpa', models.FloatField(help_text='Sea-level pressure in hectopascals.')),
                ('wind_speed_kph', models.FloatField(help_text='Wind speed in km/h.')),
                ('wind_direction_deg', models.PositiveSmallIntegerField(blank=True, help_text='Wind bearing, 0-359 degrees.', null=True)),
                ('precipitation_mm', models.FloatField(default=0, help_text='Precipitation over the hour in millimetres.')),
                ('cloud_cover', models.PositiveSmallIntegerField(default=0, help_text='Cloud cover, 0-100%.')),
                ('condition', models.CharField(choices=[('clear', 'Clear'), ('partly_cloudy', 'Partly cloudy'), ('cloudy', 'Cloudy'), ('rain', 'Rain'), ('thunderstorm', 'Thunderstorm'), ('snow', 'Snow'), ('fog', 'Fog')], default='clear', max_length=16)),
            ],
            options={
                'verbose_name_plural': 'hourly weather',
                'ordering': ('city', 'observed_at'),
            },
        ),
        migrations.DeleteModel(
            name='Log',
        ),
        migrations.AddConstraint(
            model_name='city',
            constraint=models.UniqueConstraint(fields=('name', 'country'), name='unique_city_per_country'),
        ),
        migrations.AddField(
            model_name='hourlyweather',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hourly_readings', to='busybee.city'),
        ),
        migrations.AddIndex(
            model_name='hourlyweather',
            index=models.Index(fields=['city', 'observed_at'], name='weather_city_hour_idx'),
        ),
        migrations.AddConstraint(
            model_name='hourlyweather',
            constraint=models.UniqueConstraint(fields=('city', 'observed_at'), name='unique_reading_per_city_hour'),
        ),
    ]
