# Generated by Django 6.0.7 on 2026-07-28 03:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busybee', '0003_city_hourlyweather_delete_log_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyWeatherSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='The calendar day this summary covers.')),
                ('temperature_min_c', models.FloatField()),
                ('temperature_max_c', models.FloatField()),
                ('temperature_mean_c', models.FloatField()),
                ('humidity_mean', models.FloatField(help_text='Mean relative humidity, 0-100%.')),
                ('pressure_mean_hpa', models.FloatField()),
                ('wind_speed_max_kph', models.FloatField()),
                ('precipitation_total_mm', models.FloatField(help_text='Total precipitation over the day in millimetres.')),
                ('dominant_condition', models.CharField(choices=[('clear', 'Clear'), ('partly_cloudy', 'Partly cloudy'), ('cloudy', 'Cloudy'), ('rain', 'Rain'), ('thunderstorm', 'Thunderstorm'), ('snow', 'Snow'), ('fog', 'Fog')], help_text='The most frequent hourly condition for the day.', max_length=16)),
                ('reading_count', models.PositiveSmallIntegerField(default=0, help_text='Number of hourly readings this summary is based on.')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_summaries', to='busybee.city')),
            ],
            options={
                'verbose_name_plural': 'daily weather summaries',
                'ordering': ('city', 'date'),
                'indexes': [models.Index(fields=['city', 'date'], name='weather_city_day_idx')],
                'constraints': [models.UniqueConstraint(fields=('city', 'date'), name='unique_summary_per_city_day')],
            },
        ),
    ]
